kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: devops-mysql-ds
  namespace: ks-devops-test
  labels:
    app: devopstest
    container: devops-mysql
    group: devopstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopstest
      container: devops-mysql
      group: devopstest
  template:
    metadata:
      labels:
        app: devopstest
        container: devops-mysql
        group: devopstest
    spec:
      volumes:
        - name: devops-mysql-data
          persistentVolumeClaim:
            claimName: devops-mysql-pvc
      containers:
        - name: devops-mysql
          image: mysql:5.6
          ports:
            - name: tcp-3306
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: 10m
              memory: 1000Mi
          volumeMounts:
            - name: devops-mysql-data
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities: {}
            privileged: false
            procMount: Default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ''
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
