kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devops-wordpress-pvc
  namespace: ks-devops-test
  labels:
    app: devopstest
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  volumeMode: Filesystem